### PR TITLE
fix: add PPM to PATH

### LINKED ISSUE #23: Cant't execute Pulsar commands with the flatpak version
Hello!
For some reason I can not execute Pulsar commands in my terminal with the flatpak version installed.
Is this issue already known? Could this be a permission issue?
Flatpak Version: 1.110.0
Last update: 16th october 2023
Runtime: org.freedesktop.Sdk/x86_64/22.08
Distro: EndeavourOS with Gnome and XFCE
My Gnome session uses Wayland, my XFCE session uses X11/Xorg

### PR DESCRIPTION
**Pull request by cat-master21**
Closes #23

### CODE REVIEW

**Comment by confused-Techie** [comment]
Amazing response time @cat-master21!

**Comment by cat-master21** [comment]
Thanks @confused-Techie, do you think #23 would also be an issue for the DEB version since it does not install `ppm` to the user's PATH?

**Comment by confused-Techie** [comment]
@cat-master21 That's a good question.
I'm not familiar on the Linux side of things enough, but I'll give this a ping to those folks to get their thoughts

**Comment by DeeDeeG** [comment]
We _should_ be putting `ppm` on the user's PATH when installing the `.deb`...

- https://github.com/pulsar-edit/pulsar/blob/c16743e2c43a885c199077547635e59a56a8d7f5/script/electron-builder.js#L146-L147
- https://github.com/pulsar-edit/pulsar/blob/c16743e2c43a885c199077547635e59a56a8d7f5/script/post-install.sh#L12-L19

If it's not working, that's a bug. Was working for me last I checked... I think? (It's been a while.)

**Pull request merged**
